export type MinecraftAvailableTasks =
	| 'BanUser'
	| 'BanUserIP'
	| 'CheckForUpdates'
	| 'GiveXP'
	| 'IfCondition'
	| 'KickUser'
	| 'KillPlayer'
	| 'MakeGETRequest'
	| 'Fabulous'
	| 'MakePOSTRequest'
	| 'DiscordMessage'
	| 'SlackMessage'
	| 'PushMessage'
	| 'PushMessageChannel'
	| 'Sleep'
	| 'RestartIfEmpty'
	| 'Restart'
	| 'RestoreBackup'
	| 'CommandWithWarnings'
	| 'ScheduleEmptyUpdate'
	| 'SendGlobalTitle'
	| 'SendUserMessage'
	| 'SendServerMessage'
	| 'SendTitle'
	| 'SendWakeOnLan'
	| 'SendConsoleAdv'
	| 'SendMail'
	| 'SendConsole'
	| 'SendMultipleConsole'
	| 'SetGameTime'
	| 'TakeBackupWhileDown'
	| 'Start'
	| 'StopIfEmpty'
	| 'Stop'
	| 'SmitePlayer'
	| 'TakeBackup'
	| 'TakeStickyBackup'
	| 'TeleportToCoords'
	| 'TeleportToPlayer'
	| 'UpdateAndRestart'
	| 'Wait'
	| 'Weaken'
	| 'SaveChanges';

export type MinecraftAvailableTriggers =
	| 'A backup finishes archiving.'
	| 'A backup finishes restoring.'
	| 'A backup has failed.'
	| 'A backup has started.'
	| 'A player achieves an advancement'
	| 'A player commits suicide'
	| 'A player gets an achievement'
	| 'A player is killed by an NPC'
	| 'A player is killed by another player'
	| 'A player joins the server'
	| 'A player joins the server for the first time'
	| 'A player joins the server while it was empty'
	| 'A player leaves the server'
	| 'A player performs an action'
	| 'A player sends a chat message'
	| "A player tries to join the server while it's sleeping"
	| 'A player who has previously visited rejoins the server'
	| 'A scheduled backup finishes archiving.'
	| 'The application state changes'
	| 'The last player leaves the server'
	| 'The Minecraft server is unable to keep up'
	| 'The Minecraft server repeatedly fails to start'
	| 'The Minecraft Server stops unexpectedly'
	| 'The Minecraft Server watchdog forced a shutdown (server unresponsive)'
	| 'The server enters sleep mode'
	| 'The server wakes up from sleep mode due to player connect';

export type GenericModuleAvailableTasks =
	| 'CheckForUpdates'
	| 'IfCondition'
	| 'MakeGETRequest'
	| 'MakePOSTRequest'
	| 'DiscordMessage'
	| 'SlackMessage'
	| 'PushMessage'
	| 'PushMessageChannel'
	| 'Restart'
	| 'RestartIfEmpty'
	| 'RestoreBackup'
	| 'CommandWithWarnings'
	| 'ScheduleEmptyUpdate'
	| 'WriteLine'
	| 'SendWakeOnLan'
	| 'SendMail'
	| 'TakeBackupWhileDown'
	| 'Start'
	| 'Stop'
	| 'StopIfEmpty'
	| 'TakeBackup'
	| 'TakeStickyBackup'
	| 'Update'
	| 'UpdateAndRestart'
	| 'Wait';

export type GenericModuleAvailableTriggers =
	| 'A scheduled backup finishes archiving.'
	| 'A user sends a chat message'
	| 'An update is available via SteamCMD'
	| 'An update is NOT available via SteamCMD'
	| 'The first user joins the server'
	| 'The last user leaves the server';
